// SignUp
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";

// SignIn
export const AUTH_SIGNIN = "AUTH_SIGNIN";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNIN_FAILURE = "AUTH_SIGNIN_FAILURE";

// SignOut
export const AUTH_SIGNOUT = "AUTH_SIGNOUT";
export const AUTH_SIGNOUT_ERROR = "AUTH_SIGNOUT_ERROR";

// SignDestroy
export const AUTH_SIGN_DESTROY = "AUTH_SIGN_DESTROY";
export const AUTH_SIGN_DESTROY_ERROR = "AUTH_SIGN_DESTROY_ERROR";

// SignUpdate
export const AUTH_SIGN_UPDATE = "AUTH_SIGN_UPDATE";
export const AUTH_SIGN_UPDATE_ERROR = "AUTH_SIGN_UPDATE_ERROR";

// SignIn Button is clicked
export const SIGNIN_BTN_IS_CLICKED = "SIGNIN_BTN_IS_CLICKED";

// SignUp Button is clicked
export const SIGNUP_BTN_IS_CLICKED = "SIGNUP_BTN_IS_CLICKED";

//Confirm Password At MyInfo
export const CONFIRM = "CONFIRM";
export const CONFIRM_PWD = "CONFIRM_PWD";
export const CONFIRM_PWD_ERROR = "CONFIRM_PWD_ERROR";

//Profile Add
export const PROFILE_ADD = "ADD_PROFILE";
export const PROFILE_ADD_SUCCESS = "ADD_PROFILE_SUCCESS";
export const PROFILE_ADD_FAILURE = "ADD_PROFILE_FAILURE";

//Profile Display
export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_FAILURE = 'PROFILE_LOAD_FAILURE';